testbot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 50.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 50.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 50.0, i: 0.01, d: 10.0}

 # Velocity Controller ---------------------------------------
  joint4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: joint4
    pid: {p: 1.0, i: 0.0, d: 0.0}

 # Position Controllers ---------------------------------------
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 5.0, i: 0.01, d: 1.0}